In [1]:
import polars as pl
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
bureau = pl.read_csv("../data/raw/bureau.csv")

bureau.head()

shape: (5, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ SK_ID_CUR ┆ SK_ID_BUR ┆ CREDIT_AC ┆ CREDIT_CU ┆ … ┆ AMT_CREDI ┆ CREDIT_TY ┆ DAYS_CRED ┆ AMT_ANNU │
│ R         ┆ EAU       ┆ TIVE      ┆ RRENCY    ┆   ┆ T_SUM_OVE ┆ PE        ┆ IT_UPDATE ┆ ITY      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ RDUE      ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ i64       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 215354    ┆ 5714462   ┆ Closed    ┆ currency  ┆ … ┆ 0.0       ┆ Consumer  ┆ -131      ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆ credit    ┆           ┆          │
│ 215354    ┆ 5714463   ┆ Active    ┆ currency  ┆ … ┆ 0.0       ┆ Credit    ┆ -20       ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆ card      ┆           ┆          │
│ 215354    ┆ 5714464   ┆ Active    ┆ currency  ┆ … ┆ 0.0       ┆ Consumer  ┆ -16       ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆ credit    ┆           ┆          │
│ 215354    ┆ 5714465   ┆ Active    ┆ currency  ┆ … ┆ 0.0       ┆ Credit    ┆ -16       ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆ card      ┆           ┆          │
│ 215354    ┆ 5714466   ┆ Active    ┆ currency  ┆ … ┆ 0.0       ┆ Consumer  ┆ -21       ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆ credit    ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
bureau.schema

Schema([('SK_ID_CURR', Int64),
        ('SK_ID_BUREAU', Int64),
        ('CREDIT_ACTIVE', String),
        ('CREDIT_CURRENCY', String),
        ('DAYS_CREDIT', Int64),
        ('CREDIT_DAY_OVERDUE', Int64),
        ('DAYS_CREDIT_ENDDATE', Float64),
        ('DAYS_ENDDATE_FACT', Float64),
        ('AMT_CREDIT_MAX_OVERDUE', Float64),
        ('CNT_CREDIT_PROLONG', Int64),
        ('AMT_CREDIT_SUM', Float64),
        ('AMT_CREDIT_SUM_DEBT', Float64),
        ('AMT_CREDIT_SUM_LIMIT', Float64),
        ('AMT_CREDIT_SUM_OVERDUE', Float64),
        ('CREDIT_TYPE', String),
        ('DAYS_CREDIT_UPDATE', Int64),
        ('AMT_ANNUITY', String)])

In [4]:
bureau_balance = pl.read_csv("../data/raw/bureau_balance.csv")

bureau_balance.head()

shape: (5, 3)
┌──────────────┬────────────────┬────────┐
│ SK_ID_BUREAU ┆ MONTHS_BALANCE ┆ STATUS │
│ ---          ┆ ---            ┆ ---    │
│ i64          ┆ i64            ┆ str    │
╞══════════════╪════════════════╪════════╡
│ 5715448      ┆ 0              ┆ C      │
│ 5715448      ┆ -1             ┆ C      │
│ 5715448      ┆ -2             ┆ C      │
│ 5715448      ┆ -3             ┆ C      │
│ 5715448      ┆ -4             ┆ C      │
└──────────────┴────────────────┴────────┘

In [5]:
bureau_balance.schema

Schema([('SK_ID_BUREAU', Int64),
        ('MONTHS_BALANCE', Int64),
        ('STATUS', String)])

In [6]:
bb_numeric = bureau_balance.with_columns([
    pl.col("STATUS")
    .replace({"C":0, "X":0})
    .cast(pl.Int64,strict=False)
    .fill_null(0)
    .alias("STATUS_NUMERICAL")
])

bb_features = (
    bb_numeric
    .group_by("SK_ID_BUREAU")
    .agg([
        pl.len().alias("bb_total_months_tracked"),
        pl.col("STATUS_NUMERICAL").max().alias("bb_worst_status"),
        pl.col("STATUS_NUMERICAL").filter(pl.col("STATUS_NUMERICAL") > 0).len().alias("bb_months_overdue_count"),
        pl.col("STATUS_NUMERICAL").filter(pl.col("MONTHS_BALANCE") >= -6).max().alias("bb_worst_status_last_6m")
    ])
)

bb_features.head()

shape: (5, 5)
┌──────────────┬─────────────────────┬─────────────────┬─────────────────────┬─────────────────────┐
│ SK_ID_BUREAU ┆ bb_total_months_tra ┆ bb_worst_status ┆ bb_months_overdue_c ┆ bb_worst_status_las │
│ ---          ┆ cked                ┆ ---             ┆ ount                ┆ t_6m                │
│ i64          ┆ ---                 ┆ i64             ┆ ---                 ┆ ---                 │
│              ┆ u32                 ┆                 ┆ u32                 ┆ i64                 │
╞══════════════╪═════════════════════╪═════════════════╪═════════════════════╪═════════════════════╡
│ 6707231      ┆ 18                  ┆ 0               ┆ 0                   ┆ 0                   │
│ 6195629      ┆ 12                  ┆ 0               ┆ 0                   ┆ 0                   │
│ 5046462      ┆ 83                  ┆ 0               ┆ 0                   ┆ 0                   │
│ 6013833      ┆ 51                  ┆ 1               ┆ 8                   ┆ 0                   │
│ 5242293      ┆ 22                  ┆ 0               ┆ 0                   ┆ 0                   │
└──────────────┴─────────────────────┴─────────────────┴─────────────────────┴─────────────────────┘

In [7]:
bureau_combined = bureau.join(bb_features, on="SK_ID_BUREAU", how="left")

bureau_final_features = (
    bureau_combined
    .group_by("SK_ID_CURR")
    .agg([pl.len().alias("bureau_loan_count"),
          pl.col("CREDIT_TYPE").n_unique().alias("bureau_loan_types"),
          
          pl.col("DAYS_CREDIT").max().alias("bureau_days_since_last_loan"),
          pl.col("DAYS_CREDIT").min().alias("bureau_days_since_first_loan"),
          
          pl.col("AMT_CREDIT_SUM").mean().alias("bureau_avg_credit"),
          pl.col("AMT_CREDIT_SUM_DEBT").sum().alias("total_debt"),
          pl.col("AMT_CREDIT_SUM").sum().alias("total_credit"),
          
          pl.col("AMT_CREDIT_SUM_DEBT").filter(pl.col("CREDIT_ACTIVE") == "Active").sum().alias("bureau_active_debt"),
          (pl.col("AMT_CREDIT_SUM_DEBT").sum() / (pl.col("AMT_CREDIT_SUM").sum() + 1e-5)).alias("debt_to_credit_ratio"),
          
          pl.col("CREDIT_DAY_OVERDUE").max().alias("bureau_max_overdue"),
          pl.col("AMT_CREDIT_SUM_OVERDUE").sum().alias("bureau_total_amt_overdue"),
          pl.col("CNT_CREDIT_PROLONG").sum().alias("bureau_total_prolong_count"),
          
          pl.col("bb_worst_status").max().fill_null(0).alias("bureau_global_worst_status"),
          pl.col("bb_months_overdue_count").sum().fill_null(0).alias("bureau_total_months_overdue_across_loans"),
          pl.col("bb_worst_status_last_6m").max().fill_null(0).alias("bureau_global_worst_status_last_6m")])
)

bureau_final_features.head()

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ SK_ID_CUR ┆ bureau_lo ┆ bureau_lo ┆ bureau_da ┆ … ┆ bureau_to ┆ bureau_gl ┆ bureau_to ┆ bureau_g │
│ R         ┆ an_count  ┆ an_types  ┆ ys_since_ ┆   ┆ tal_prolo ┆ obal_wors ┆ tal_month ┆ lobal_wo │
│ ---       ┆ ---       ┆ ---       ┆ last_loan ┆   ┆ ng_count  ┆ t_status  ┆ s_overdue ┆ rst_stat │
│ i64       ┆ u32       ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ _ac…      ┆ us_las…  │
│           ┆           ┆           ┆ i64       ┆   ┆ i64       ┆ i64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ u32       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 316435    ┆ 10        ┆ 2         ┆ -224      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 180906    ┆ 10        ┆ 4         ┆ -378      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 182990    ┆ 4         ┆ 2         ┆ -120      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 179072    ┆ 2         ┆ 1         ┆ -908      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 267286    ┆ 3         ┆ 2         ┆ -421      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
installment_payment = pl.read_csv("../data/raw/installments_payments.csv")
installment_payment.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_PREV ┆ SK_ID_CURR ┆ NUM_INSTAL ┆ NUM_INSTA ┆ DAYS_INST ┆ DAYS_ENTR ┆ AMT_INSTA ┆ AMT_PAYME │
│ ---        ┆ ---        ┆ MENT_VERSI ┆ LMENT_NUM ┆ ALMENT    ┆ Y_PAYMENT ┆ LMENT     ┆ NT        │
│ i64        ┆ i64        ┆ ON         ┆ BER       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆ ---        ┆ ---       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│            ┆            ┆ f64        ┆ i64       ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1054186    ┆ 161674     ┆ 1.0        ┆ 6         ┆ -1180.0   ┆ -1187.0   ┆ 6948.36   ┆ 6948.36   │
│ 1330831    ┆ 151639     ┆ 0.0        ┆ 34        ┆ -2156.0   ┆ -2156.0   ┆ 1716.525  ┆ 1716.525  │
│ 2085231    ┆ 193053     ┆ 2.0        ┆ 1         ┆ -63.0     ┆ -63.0     ┆ 25425.0   ┆ 25425.0   │
│ 2452527    ┆ 199697     ┆ 1.0        ┆ 3         ┆ -2418.0   ┆ -2426.0   ┆ 24350.13  ┆ 24350.13  │
│ 2714724    ┆ 167756     ┆ 1.0        ┆ 2         ┆ -1383.0   ┆ -1366.0   ┆ 2165.04   ┆ 2160.585  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [9]:
installment_payment.schema

Schema([('SK_ID_PREV', Int64),
        ('SK_ID_CURR', Int64),
        ('NUM_INSTALMENT_VERSION', Float64),
        ('NUM_INSTALMENT_NUMBER', Int64),
        ('DAYS_INSTALMENT', Float64),
        ('DAYS_ENTRY_PAYMENT', Float64),
        ('AMT_INSTALMENT', Float64),
        ('AMT_PAYMENT', Float64)])

In [10]:
ins_processed = installment_payment.with_columns(
    (pl.col("AMT_PAYMENT") - pl.col("AMT_INSTALMENT")).alias("ins_pay_diff"),
    (pl.col("AMT_PAYMENT") / pl.col("AMT_INSTALMENT") + 1e-5).alias("ins_pay_ratio"),
    (pl.col("DAYS_ENTRY_PAYMENT") - pl.col("DAYS_INSTALMENT")).alias("ins_day_late")
)

ins_processed.head()

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ SK_ID_PRE ┆ SK_ID_CUR ┆ NUM_INSTA ┆ NUM_INSTA ┆ … ┆ AMT_PAYME ┆ ins_pay_d ┆ ins_pay_r ┆ ins_day_ │
│ V         ┆ R         ┆ LMENT_VER ┆ LMENT_NUM ┆   ┆ NT        ┆ iff       ┆ atio      ┆ late     │
│ ---       ┆ ---       ┆ SION      ┆ BER       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ i64       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆ f64       ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1054186   ┆ 161674    ┆ 1.0       ┆ 6         ┆ … ┆ 6948.36   ┆ 0.0       ┆ 1.00001   ┆ -7.0     │
│ 1330831   ┆ 151639    ┆ 0.0       ┆ 34        ┆ … ┆ 1716.525  ┆ 0.0       ┆ 1.00001   ┆ 0.0      │
│ 2085231   ┆ 193053    ┆ 2.0       ┆ 1         ┆ … ┆ 25425.0   ┆ 0.0       ┆ 1.00001   ┆ 0.0      │
│ 2452527   ┆ 199697    ┆ 1.0       ┆ 3         ┆ … ┆ 24350.13  ┆ 0.0       ┆ 1.00001   ┆ -8.0     │
│ 2714724   ┆ 167756    ┆ 1.0       ┆ 2         ┆ … ┆ 2160.585  ┆ -4.455    ┆ 0.997952  ┆ 17.0     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
ins_features = (
    ins_processed
    .group_by("SK_ID_CURR")
    .agg([
        pl.len().alias("ins_total_installment_tracked"),
        
        pl.col("ins_pay_diff").min().alias("ins_worst_underpay"),
        pl.col("ins_pay_diff").mean().alias("ins_mean_payment_diff"),
        pl.col("ins_pay_ratio").mean().alias("ins_mean_payratio"),
        
        pl.col("ins_pay_diff").filter(pl.col("ins_pay_diff") < 0).len().alias("ins_undepayment_count"),
        
        pl.col("ins_day_late").max().alias("ins_worst_day_late"),
        pl.col("ins_day_late").mean().alias("ins_avg_day_late"),
        
        pl.col("ins_day_late").filter(pl.col("ins_day_late") > 0).len().alias("ins_late_count")
    ])
)

ins_features.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ SK_ID_CUR ┆ ins_total ┆ ins_worst ┆ ins_mean_ ┆ … ┆ ins_undep ┆ ins_worst ┆ ins_avg_d ┆ ins_late │
│ R         ┆ _installm ┆ _underpay ┆ payment_d ┆   ┆ ayment_co ┆ _day_late ┆ ay_late   ┆ _count   │
│ ---       ┆ ent_track ┆ ---       ┆ iff       ┆   ┆ unt       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ ed        ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ u32      │
│           ┆ ---       ┆           ┆ f64       ┆   ┆ u32       ┆           ┆           ┆          │
│           ┆ u32       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 151139    ┆ 6         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ -9.0      ┆ -10.33333 ┆ 0        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆          │
│ 406486    ┆ 120       ┆ -8439.795 ┆ -814.65   ┆ … ┆ 23        ┆ 27.0      ┆ -4.625    ┆ 30       │
│ 420256    ┆ 69        ┆ -12177.67 ┆ -556.3232 ┆ … ┆ 10        ┆ 11.0      ┆ -4.391304 ┆ 5        │
│           ┆           ┆ 5         ┆ 61        ┆   ┆           ┆           ┆           ┆          │
│ 270829    ┆ 98        ┆ -8325.0   ┆ 350.89025 ┆ … ┆ 17        ┆ 23.0      ┆ -6.408163 ┆ 6        │
│           ┆           ┆           ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│ 117329    ┆ 8         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0.0       ┆ -13.375   ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
credit_card_balance = pl.read_csv("../data/raw/credit_card_balance.csv")

credit_card_balance.head()

shape: (5, 23)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ SK_ID_PREV ┆ SK_ID_CURR ┆ MONTHS_BA ┆ AMT_BALAN ┆ … ┆ CNT_INSTA ┆ NAME_CONT ┆ SK_DPD ┆ SK_DPD_DE │
│ ---        ┆ ---        ┆ LANCE     ┆ CE        ┆   ┆ LMENT_MAT ┆ RACT_STAT ┆ ---    ┆ F         │
│ i64        ┆ i64        ┆ ---       ┆ ---       ┆   ┆ URE_CUM   ┆ US        ┆ i64    ┆ ---       │
│            ┆            ┆ i64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆        ┆ i64       │
│            ┆            ┆           ┆           ┆   ┆ f64       ┆ str       ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 2562384    ┆ 378907     ┆ -6        ┆ 56.97     ┆ … ┆ 35.0      ┆ Active    ┆ 0      ┆ 0         │
│ 2582071    ┆ 363914     ┆ -1        ┆ 63975.555 ┆ … ┆ 69.0      ┆ Active    ┆ 0      ┆ 0         │
│ 1740877    ┆ 371185     ┆ -7        ┆ 31815.225 ┆ … ┆ 30.0      ┆ Active    ┆ 0      ┆ 0         │
│ 1389973    ┆ 337855     ┆ -4        ┆ 236572.11 ┆ … ┆ 10.0      ┆ Active    ┆ 0      ┆ 0         │
│ 1891521    ┆ 126868     ┆ -1        ┆ 453919.45 ┆ … ┆ 101.0     ┆ Active    ┆ 0      ┆ 0         │
│            ┆            ┆           ┆ 5         ┆   ┆           ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [13]:
cc_sorted = credit_card_balance.sort(["SK_ID_CURR","MONTHS_BALANCE"])

cc_features = (
    cc_sorted
    .group_by("SK_ID_CURR")
    .agg([
        pl.len().alias("cc_months_tracked"),
        
        pl.col("AMT_DRAWINGS_CURRENT").sum().alias("cc_total_drawings_amt"),
        pl.col("AMT_DRAWINGS_CURRENT").max().alias("cc_max_single_month_drawing"),
        pl.col("CNT_DRAWINGS_CURRENT").sum().alias("cc_total_drawings_count"),
        
        pl.col("AMT_DRAWINGS_ATM_CURRENT").sum().alias("cc_total_atm_drawings_amt"),
        (pl.col("AMT_DRAWINGS_ATM_CURRENT").sum() / (pl.col("AMT_DRAWINGS_CURRENT").sum() + 1e-5)).alias("cc_atm_to_total_drawing_ratio"),
        
        pl.col("AMT_PAYMENT_CURRENT").sum().alias("cc_total_paymemt"),
        (pl.col("AMT_PAYMENT_CURRENT").sum() / (pl.col("AMT_INST_MIN_REGULARITY").sum() + 1e-5)).alias("cc_pay_to_min_inst_ratio"),
        
        pl.col("AMT_BALANCE").max().alias("cc_max_balance_ever"),
        pl.col("AMT_BALANCE").last().alias("cc_current_balance"),
        pl.col("AMT_TOTAL_RECEIVABLE").last().alias("cc_current_total_receivable"),
        
        (pl.col("AMT_BALANCE").last() / (pl.col("AMT_CREDIT_LIMIT_ACTUAL").last() + 1e-5)).alias("cc_current_utilization_ratio"),
        
        pl.col("SK_DPD").max().alias("cc_max_days_past_due"),
        pl.col("SK_DPD_DEF").max().alias("cc_max_days_past_due_with_tolerance"),
        
        pl.col("SK_DPD").filter(pl.col("SK_DPD") > 0).len().alias("cc_month_overdue_count")
    ])
    
)

cc_features.head()

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ SK_ID_CUR ┆ cc_months ┆ cc_total_ ┆ cc_max_si ┆ … ┆ cc_curren ┆ cc_max_da ┆ cc_max_da ┆ cc_month │
│ R         ┆ _tracked  ┆ drawings_ ┆ ngle_mont ┆   ┆ t_utiliza ┆ ys_past_d ┆ ys_past_d ┆ _overdue │
│ ---       ┆ ---       ┆ amt       ┆ h_drawing ┆   ┆ tion_rati ┆ ue        ┆ ue_with_t ┆ _count   │
│ i64       ┆ u32       ┆ ---       ┆ ---       ┆   ┆ o         ┆ ---       ┆ ole…      ┆ ---      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ u32      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ i64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100006    ┆ 6         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ 100011    ┆ 74        ┆ 180000.0  ┆ 180000.0  ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ 100013    ┆ 96        ┆ 571500.0  ┆ 157500.0  ┆ … ┆ 0.0       ┆ 1         ┆ 1         ┆ 1        │
│ 100021    ┆ 17        ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ 100023    ┆ 8         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
pos_cash_balance = pl.read_csv("../data/raw/POS_CASH_balance.csv")

pos_cash_balance.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────┬───────────┐
│ SK_ID_PREV ┆ SK_ID_CURR ┆ MONTHS_BAL ┆ CNT_INSTAL ┆ CNT_INSTAL ┆ NAME_CONTR ┆ SK_DPD ┆ SK_DPD_DE │
│ ---        ┆ ---        ┆ ANCE       ┆ MENT       ┆ MENT_FUTUR ┆ ACT_STATUS ┆ ---    ┆ F         │
│ i64        ┆ i64        ┆ ---        ┆ ---        ┆ E          ┆ ---        ┆ i64    ┆ ---       │
│            ┆            ┆ i64        ┆ f64        ┆ ---        ┆ str        ┆        ┆ i64       │
│            ┆            ┆            ┆            ┆ f64        ┆            ┆        ┆           │
╞════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════╪═══════════╡
│ 1803195    ┆ 182943     ┆ -31        ┆ 48.0       ┆ 45.0       ┆ Active     ┆ 0      ┆ 0         │
│ 1715348    ┆ 367990     ┆ -33        ┆ 36.0       ┆ 35.0       ┆ Active     ┆ 0      ┆ 0         │
│ 1784872    ┆ 397406     ┆ -32        ┆ 12.0       ┆ 9.0        ┆ Active     ┆ 0      ┆ 0         │
│ 1903291    ┆ 269225     ┆ -35        ┆ 48.0       ┆ 42.0       ┆ Active     ┆ 0      ┆ 0         │
│ 2341044    ┆ 334279     ┆ -35        ┆ 36.0       ┆ 35.0       ┆ Active     ┆ 0      ┆ 0         │
└────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────┴───────────┘

In [15]:
pos_sorted = pos_cash_balance.sort(["SK_ID_CURR","MONTHS_BALANCE"])

pos_features = (
    pos_sorted
    .group_by("SK_ID_CURR")
    .agg([
        pl.len().alias("pos_month_tracked"),
        
        pl.col("CNT_INSTALMENT").max().alias("pos_max_loan_term"),
        pl.col("CNT_INSTALMENT_FUTURE").last().alias("pos_current_remaining_installments"),
        
        (pl.col("CNT_INSTALMENT_FUTURE").last() / (pl.col("CNT_INSTALMENT").last() + 1e-5)).alias("pos_remaining_installment_ratio"),
        
        pl.col("SK_DPD").max().alias("pos_max_days_past_due"),
        pl.col("SK_DPD_DEF").max().alias("pos_max_days_past_due_with_tolerance"),
        
        pl.col("SK_DPD").filter(pl.col("SK_DPD") > 0).len().alias("pos_month_overdue_count")
    ])
)

pos_features.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ SK_ID_CURR ┆ pos_month_ ┆ pos_max_lo ┆ pos_curre ┆ pos_remai ┆ pos_max_d ┆ pos_max_d ┆ pos_month │
│ ---        ┆ tracked    ┆ an_term    ┆ nt_remain ┆ ning_inst ┆ ays_past_ ┆ ays_past_ ┆ _overdue_ │
│ i64        ┆ ---        ┆ ---        ┆ ing_insta ┆ allment_r ┆ due       ┆ due_with_ ┆ count     │
│            ┆ u32        ┆ f64        ┆ llm…      ┆ ati…      ┆ ---       ┆ tol…      ┆ ---       │
│            ┆            ┆            ┆ ---       ┆ ---       ┆ i64       ┆ ---       ┆ u32       │
│            ┆            ┆            ┆ f64       ┆ f64       ┆           ┆ i64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 100001     ┆ 9          ┆ 4.0        ┆ 0.0       ┆ 0.0       ┆ 7         ┆ 7         ┆ 1         │
│ 100002     ┆ 19         ┆ 24.0       ┆ 6.0       ┆ 0.25      ┆ 0         ┆ 0         ┆ 0         │
│ 100003     ┆ 28         ┆ 12.0       ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│ 100004     ┆ 4          ┆ 4.0        ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
│ 100005     ┆ 11         ┆ 12.0       ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0         ┆ 0         │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [16]:
previous_application = pl.read_csv("../data/raw/previous_application.csv")

previous_application.head()

shape: (5, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ SK_ID_PRE ┆ SK_ID_CUR ┆ NAME_CONT ┆ AMT_ANNUI ┆ … ┆ DAYS_LAST ┆ DAYS_LAST ┆ DAYS_TERM ┆ NFLAG_IN │
│ V         ┆ R         ┆ RACT_TYPE ┆ TY        ┆   ┆ _DUE_1ST_ ┆ _DUE      ┆ INATION   ┆ SURED_ON │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ VERSION   ┆ ---       ┆ ---       ┆ _APPROVA │
│ i64       ┆ i64       ┆ str       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ L        │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2030495   ┆ 271877    ┆ Consumer  ┆ 1730.43   ┆ … ┆ 300.0     ┆ -42.0     ┆ -37.0     ┆ 0.0      │
│           ┆           ┆ loans     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2802425   ┆ 108129    ┆ Cash      ┆ 25188.615 ┆ … ┆ 916.0     ┆ 365243.0  ┆ 365243.0  ┆ 1.0      │
│           ┆           ┆ loans     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2523466   ┆ 122040    ┆ Cash      ┆ 15060.735 ┆ … ┆ 59.0      ┆ 365243.0  ┆ 365243.0  ┆ 1.0      │
│           ┆           ┆ loans     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2819243   ┆ 176158    ┆ Cash      ┆ 47041.335 ┆ … ┆ -152.0    ┆ -182.0    ┆ -177.0    ┆ 1.0      │
│           ┆           ┆ loans     ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1784265   ┆ 202054    ┆ Cash      ┆ 31924.395 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ loans     ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
prev_sorted = previous_application.sort(["SK_ID_CURR", "DAYS_DECISION"])

prev_features = (
    prev_sorted
    .group_by("SK_ID_CURR")
    .agg([
        pl.len().alias("prev_total_applications"),
        
        pl.col("DAYS_DECISION").max().alias("prev_days_since_last_decision"),
        pl.col("DAYS_DECISION").min().alias("prev_days_since_first_decision"),
        
        pl.col("AMT_APPLICATION").sum().alias("prev_total_amt_asked"),
        pl.col("AMT_CREDIT").sum().alias("prev_total_amt_approved"),
        (pl.col("AMT_CREDIT").sum() / (pl.col("AMT_APPLICATION").sum() + 1e-5)).alias("prev_credit_to_application_ratio"),
        pl.col("AMT_ANNUITY").mean().alias("prev_avg_annuity_amt"),
        pl.col("RATE_DOWN_PAYMENT").mean().alias("prev_avg_down_payment_rate"),
        
        pl.col("CNT_PAYMENT").mean().alias("prev_avg_loan_term_months"),
        
        pl.col("NAME_CONTRACT_STATUS").filter(pl.col("NAME_CONTRACT_STATUS") == "Refused").len().alias("prev_count_refused"),
        pl.col("NAME_CONTRACT_STATUS").filter(pl.col("NAME_CONTRACT_STATUS") == "Approved").len().alias("prev_count_approved"),
        pl.col("NAME_CONTRACT_STATUS").filter(pl.col("NAME_CONTRACT_STATUS") == "Canceled").len().alias("prev_count_canceled"),
        
        (pl.col("NAME_CONTRACT_STATUS").filter(pl.col("NAME_CONTRACT_STATUS") == "Refused").len() / pl.len()).alias("prev_rejection_rate"),
        pl.col("NAME_CONTRACT_STATUS").last().alias("prev_most_recent_status")
    ])
)

prev_features = prev_features.to_dummies(columns=["prev_most_recent_status"])

prev_features.head()

shape: (5, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ SK_ID_CUR ┆ prev_tota ┆ prev_days ┆ prev_days ┆ … ┆ prev_most ┆ prev_most ┆ prev_most ┆ prev_mos │
│ R         ┆ l_applica ┆ _since_la ┆ _since_fi ┆   ┆ _recent_s ┆ _recent_s ┆ _recent_s ┆ t_recent │
│ ---       ┆ tions     ┆ st_decisi ┆ rst_decis ┆   ┆ tatus_App ┆ tatus_Can ┆ tatus_Ref ┆ _status_ │
│ i64       ┆ ---       ┆ on        ┆ ion       ┆   ┆ rov…      ┆ cel…      ┆ use…      ┆ Unused…  │
│           ┆ u32       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ i64       ┆ i64       ┆   ┆ u8        ┆ u8        ┆ u8        ┆ u8       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100001    ┆ 1         ┆ -1740     ┆ -1740     ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0        │
│ 100002    ┆ 1         ┆ -606      ┆ -606      ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0        │
│ 100003    ┆ 3         ┆ -746      ┆ -2341     ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0        │
│ 100004    ┆ 1         ┆ -815      ┆ -815      ┆ … ┆ 1         ┆ 0         ┆ 0         ┆ 0        │
│ 100005    ┆ 2         ┆ -315      ┆ -757      ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
print(bureau_final_features["SK_ID_CURR"].is_unique().all())
print(ins_features["SK_ID_CURR"].is_unique().all())
print(cc_features["SK_ID_CURR"].is_unique().all())
print(pos_features["SK_ID_CURR"].is_unique().all())
print(prev_features["SK_ID_CURR"].is_unique().all())

True
True
True
True
True

In [19]:
application_train = pl.read_csv("../data/raw/application_train.csv")
application_test = pl.read_csv("../data/raw/application_test.csv")

def assemble_master_dataset(base_application_df, bureau_df, ins_df, cc_df, pos_df, prev_df):
    """
    Sequentially joins all engineered feature tables onto a base application dataframe (train or test).
    """
    return (
        base_application_df
        .join(bureau_df, on="SK_ID_CURR", how="left")
        .join(ins_df, on="SK_ID_CURR", how="left")
        .join(cc_df, on="SK_ID_CURR", how="left")
        .join(pos_df, on="SK_ID_CURR", how="left")
        .join(prev_df, on="SK_ID_CURR", how="left")
    )

train_complete = assemble_master_dataset(
    application_train, bureau_final_features, ins_features, cc_features, pos_features, prev_features
)

test_complete = assemble_master_dataset(
    application_test, bureau_final_features, ins_features, cc_features, pos_features, prev_features
)

print(f"Train Shape: {train_complete.shape}")
print(f"Test Shape: {test_complete.shape}")

Train Shape: (307511, 184)
Test Shape: (48744, 183)